export const defaultConfig = {
    names: "Louie & Florie",
    dateString: "July 4th, 2026",
    dateIso: "2026-07-04T00:00:00",
    location: "Cebu, Philippines",
    heroImage: "https://images.unsplash.com/photo-1519741497674-611481863552?ixlib=rb-4.0.3&auto=format&fit=crop&w=1920&q=80",
    heroScrollText: "Scroll",
    rsvpMode: 'form',
    rsvpExternalLink: "https://forms.google.com/",
    rsvpDeadline: "May 1st, 2026",
    rsvpImage: "https://images.unsplash.com/photo-1606216794074-735e91aa2c92?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    instagram: "#",
    facebook: "#",
    messenger: "#",
    contact: "#",
    shareTitle: "You're Invited to Our Wedding!",
    shareDescription: "We invite you to celebrate our special day with us. Click to view our wedding website for more details.",
    showFloatingShare: true,
    logoText: "",
    websiteTitle: "",
    showOpeningScreen: true,
    navMaxLinks: 6,
    navGlassmorphism: true,
    navLogoHeight: 48,
    navTransparentInitial: true,
    passcode: "admin",
    colorPalette: [
        { name: "Dusty Rose", hex: "#E6D2B5" },
        { name: "Sage Green", hex: "#8C9E8C" },
        { name: "Terracotta", hex: "#C76D55" },
        { name: "Cream", hex: "#FDFBF7" },
        { name: "Charcoal", hex: "#43342E" }
    ],
    savedPalettes: [],
    dressCode: "Semi-Formal Attire",
    dressCodeDescription: "We kindly request that our guests dress in semi-formal attire.",
    guestList: [],
    notes: [],
    storyTitle: "Our Journey",
    storySubtitle: "Since 2018",
    story: [
        { date: "June 15, 2018", title: "The Encounter", description: "We met at a coffee shop in downtown. It started with a spilled latte and ended with a conversation that lasted for hours." },
        { date: "December 24, 2022", title: "Building a Home", description: "After a year and a half of adventures, we moved in together. Our first apartment was small, but full of love (and plants)." },
        { date: "August 10, 2024", title: "The Promise", description: "On a sunset hike overlooking the ocean, Louie got down on one knee. It was the easiest question Florie ever had to answer." }
    ],
    eventsTitle: "The Events",
    eventsSubtitle: "Save the Date",
    timeline: [
        { time: "1:00 PM", title: "Preparation", description: "Bridal party getting ready and photos at the Hotel Suite.", icon: "camera" },
        { time: "3:00 PM", title: "Wedding Ceremony", description: "Processional and exchange of vows at St. Thérèse Chapel.", icon: "heart" },
        { time: "4:30 PM", title: "Cocktails & Pictorials", description: "Enjoy drinks and grazing table at the Garden while the family takes photos.", icon: "wine" },
        { time: "6:00 PM", title: "Grand Entrance", description: "Welcoming Mr. & Mrs. Mendez to the Reception Hall.", icon: "music" },
        { time: "6:30 PM", title: "Dinner Feast", description: "A sumptuous buffet dinner accompanied by acoustic serenades.", icon: "utensils" },
        { time: "8:00 PM", title: "Cake Cutting & Toasts", description: "Traditional cutting of the cake and messages from loved ones.", icon: "wine" },
        { time: "9:00 PM", title: "Party Time", description: "Open dance floor and music under the stars!", icon: "music" }
    ],
    events: [
        { title: "Welcome Party", time: "Friday, July 3 • 6:00 PM", description: "Join us for cocktails and hors d'oeuvres to kick off the celebration.", location: "The Gardens", mapLink: "https://maps.google.com", image: "https://images.unsplash.com/photo-1558636508-e0db3836bd1b?auto=format&fit=crop&w=800&q=80", icon: "wine" },
        { title: "The Ceremony", time: "Saturday, July 4 • 2:00 PM", description: "We exchange vows followed by dinner and dancing under the stars.", location: "St. Thérèse", mapLink: "https://maps.google.com", image: "https://images.unsplash.com/photo-1548624298-967faff0d3b4?auto=format&fit=crop&w=800&q=80", icon: "heart" },
        { title: "Reception", time: "Saturday, July 4 • 6:00 PM", description: "Dinner, dancing, and drinks to celebrate the newlyweds.", location: "Reception Hall", mapLink: "https://maps.google.com", image: "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=800&q=80", icon: "music" }
    ],
    entourageTitle: "The Entourage",
    entourageSubtitle: "Wedding Party",
    groomParents: "Mr. Rolando & Mrs. Elena Mendez",
    brideParents: "Mr. Francisco & Mrs. Maria Santos",
    bestMan: "Michael James",
    maidOfHonor: "Sarah Jean",
    groomsmen: ["Adam Driver", "Ben Affleck", "Chris Evans", "David Beckham"],
    bridesmaids: ["Anna Smith", "Bella Ciao", "Cara Delevingne", "Diane Lane"],
    principalSponsors: [
        { mr: "Mr. Juan Dela Cruz", mrs: "Mrs. Maria Dela Cruz" },
        { mr: "Mr. Pedro Santos", mrs: "Mrs. Ana Santos" },
        { mr: "Mr. Jose Rizal", mrs: "Mrs. Josephine Bracken" }
    ],
    secondarySponsors: [
        { role: "Candle", names: "John & Jane" },
        { role: "Veil", names: "Mark & Mary" },
        { role: "Cord", names: "Luke & Lucy" }
    ],
    bearers: [
        { role: "Ring", name: "Little Mr. C" },
        { role: "Coin", name: "Little Mr. D" },
        { role: "Bible", name: "Little Mr. E" }
    ],
    flowerGirls: ["Little Miss A", "Little Miss B", "Little Miss C"],
    offertory: ["Family A", "Family B"],
    entouragePalette: {
        bestMan: "#43342E",
        groomsmen: "#43342E",
        maidOfHonor: "#E6D2B5",
        bridesmaid: "#E6D2B5",
        parents: "#8C9E8C",
        bearers: "#43342E"
    },
    entourageGroups: [],
    galleryImages: [
        "https://images.unsplash.com/photo-1621621667797-e06afc217fb0?auto=format&fit=crop&w=600&q=90",
        "https://images.unsplash.com/photo-1530023367847-a683933f4172?auto=format&fit=crop&w=600&q=90",
        "https://images.unsplash.com/photo-1520854221256-17451cc330e7?auto=format&fit=crop&w=600&q=90",
        "https://images.unsplash.com/photo-1535295972055-1c762f4483e5?auto=format&fit=crop&w=600&q=90",
        "https://images.unsplash.com/photo-1516961642265-531546e84af2?auto=format&fit=crop&w=600&q=90",
        "https://images.unsplash.com/photo-1522673607200-1645062cd958?auto=format&fit=crop&w=600&q=90",
        "https://images.unsplash.com/photo-1519225421980-715cb0202128?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=90",
        "https://images.unsplash.com/photo-1607193384230-25e635834331?auto=format&fit=crop&w=600&q=90"
    ],
    videosTitle: "Our Memories",
    videosSubtitle: "SDE & Prenup Videos",
    videos: [
        { id: 'prenup', title: "Prenup Video", url: "", type: 'youtube' },
        { id: 'sde', title: "Same Day Edit (SDE)", url: "", type: 'youtube' }
    ],
    registryTitle: "Gift Registry",
    registrySubtitle: "Love & Support",
    registryInstruction: "Your presence is the greatest gift, but if you wish to honor us with a gift, we've set up a registry for your convenience.",
    registryItems: [
        { type: 'bank', accountName: "Louie Mendez", accountNumber: "1234-5678-90", bankName: "BDO Unibank", qrCode: "", label: "Bank Transfer" },
        { type: 'ewallet', accountName: "Florie Santos", accountNumber: "0917-000-0000", bankName: "GCash", qrCode: "", label: "GCash" }
    ],
    mapTitle: "Venue Map",
    mapSubtitle: "Church to Reception",
    mapEmbedUrl: "https://www.google.com/maps/embed?pb=!1m28!1m12!1m3!1d31405.021074747424!2d123.8824855877843!3d10.33166881775791!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!4m13!3e0!4m5!1s0x33a998b965e52569%3A0x11218408f6d8995c!2sBasilica%20Minore%20del%20Santo%20Ni%C3%B1o%20de%20Cebu!3m2!1d10.2941913!2d123.9021183!4m5!1s0x33a9992186481351%3A0xc6360f08960851ec!2sCasino%20Espa%C3%B1ol%20de%20Cebu!3m2!1d10.312999999999999!2d123.9024042!5e0!3m2!1sen!2sph!4v1716750000000!5m2!1sen!2sph",
    mapDestination: "Casino Español de Cebu, V. Ranudo St, Cebu City",
    mapInstructions: "The reception is approximately 15-20 minutes away from the church by car. Plenty of parking is available at the venue.",
    guestbookTitle: "Guestbook",
    guestbookSubtitle: "Wishes & Love",
    guestbookMessages: [],
    weatherEnabled: false,
    weatherCity: "Cebu City",
    weatherApiKey: "",
    faqsTitle: "Frequently Asked Questions",
    faqsSubtitle: "Everything You Need to Know",
    faqs: [
        { question: "What is the dress code?", answer: "The dress code is Semi-Formal. We suggest a suit and tie for men and a cocktail dress for women." },
        { question: "Can I bring a plus one?", answer: "Due to venue capacity, we can only accommodate the guests listed on your invitation. We appreciate your understanding!" },
        { question: "Is there parking available?", answer: "Yes, Casino Español provides ample parking for all our wedding guests." },
        { question: "What time should I arrive?", answer: "The ceremony starts promptly at 3:00 PM. We recommend arriving 15-20 minutes early to find your seat." }
    ],
    sectionOrder: [
        { id: 'story', label: 'Our Story', visible: true },
        { id: 'timeline', label: 'Program', visible: true },
        { id: 'weather', label: 'Weather', visible: true },
        { id: 'faq', label: 'FAQ', visible: true },
        { id: 'entourage', label: 'Entourage', visible: true },
        { id: 'palette', label: 'Color Palette', visible: true },
        { id: 'gallery', label: 'Gallery', visible: true },
        { id: 'registry', label: 'Gift Registry', visible: true },
        { id: 'videos', label: 'Videos', visible: true },
        { id: 'rsvp', label: 'RSVP', visible: true },
        { id: 'events', label: 'Events', visible: true },
        { id: 'map', label: 'Venue Map', visible: true },
        { id: 'guestbook', label: 'Guestbook', visible: true }
    ]
};